name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Css and Javascript
        run: |
          npm install
          npm run prod
      - name: Configure PHP 8.1.4
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
